### ISSUE TITLE
Currencies are defined arbitrarily, rather than requiring 'creation' first

### ISSUE THREAD

**Issue by lokka30** [TheNewEconomy/VaultUnlockedAPI#11]
Unlike accounts in the API (which require creation before use), currencies can just be arbitrarily defined when calling methods e.g. getBalance, has, etc.

I propose currencies have to be created before they can be used.

**Comment by creatorfromhell** [comment]
The issue with providing a creation method, as opposed to the plugins using the has and default in connection, is that each plugin has different attributes for what makes up a currency.

**Comment by lokka30** [comment]
I see what you mean. In this case, creating currencies will be defined purely by the economy provider.
