### ISSUE TITLE
Problem with format?

### ISSUE THREAD

**Issue by L-Risk** [TheNewEconomy/VaultUnlockedAPI#8]
I don't know if the problem is mine or Vault's, but I have integrated my own EconomySystem with your Vault API. Now I get the message from a public plugin that says: 
public @NotNull String format(BigDecimal bigDecimal)

the format must be a double. I've tried a few things now but I'm at a loss

**Comment by creatorfromhell** [comment]
> I don't know if the problem is mine or Vault's, but I have integrated my own EconomySystem with your Vault API. Now I get the message from a public plugin that says: public @NotNull String format(BigDecimal bigDecimal)
> 
> the format must be a double. I've tried a few things now but I'm at a loss

Make sure they are using vault unlocked and not normal vault on the plugin youre testing or implement both adapters
