### ISSUE TITLE
Suggestion: Component support for Economy#format

### ISSUE THREAD

**Issue by KabanFriends** [TheNewEconomy/VaultUnlockedAPI#9]
I think it would be nice if Economy#format had an API to output Adventure Components instead of a String

**Comment by creatorfromhell** [comment]
> I think it would be nice if Economy#format had an API to output Adventure Components instead of a String

This is something I've been thinking about adding, I've mostly just been thinking about the implementation itself. Will probably have something tomorrow/this week for it.

**Comment by creatorfromhell** [comment]
Added in [69b46bf](https://github.com/TheNewEconomy/VaultUnlockedAPI/commit/69b46bf05cbbbdab4a077f5088033fbe4173892c)
